### ISSUE TITLE
InAppBrowser for authentication not functioning

### ISSUE THREAD

**Issue by TillaTheHun0** [mynameismiek/flick-client#3]
This issue is to track the discussion and remediation of the InAppBrowser used for authentication into the app. 

Currently the InAppBrowser does not function correctly. I am not able to open the InAppBrowser, so that it can hit the appropriate auth endpoint. I tried injecting the provider into the `app` module to no avail.

```
Unknown provider: $cordovaInAppBrowserProvider <- $cordovaInAppBrowser <- loginCtrl
```

Referenced by PR mynameismiek/flick-client#2

**Comment by TillaTheHun0** [comment]
Fix in  e4f054e  the InAppBrowser will pop up to authenticate with FB. Not closing the issue though bc we still have to extract the token from the browser. Still working on that.

**Comment by eears100** [comment]
So I fixed the issue with getting the token from the inappbrowser window. Might be some better way but it works. i figure it can be revisited at some point. It's in a branch called inappbrower-return-token. I didn't know what we needed to do with the token so at the moment it just prints it the screen. Once thats determined someone can do a pull request. Note: not gonna work in browser which makes it a pain to test - gotta change the ip in controller.js as well as make sure it is in the callback urls in FB dev portal.

**Comment by TillaTheHun0** [comment]
LGTM. Neither Mike or myself have had a chance to look at this since we have both been busy, so thanks for taking the reins on it. Also just using window.open as opposed to a plugin like $cordovaInAppBrowser is cool too. I don't foresee it causing any issues, but if it does the adjustment wouldn't be too drastic since the cordova plugin is essentially just a wrapper around window. Could you submit a PR from your branch to master?

**Comment by TillaTheHun0** [comment]
ps: I'm doing this form my phone.
